#
# gp-ncs-devenv
# Copyright (c) 2023-2024, Greg PFISTER. MIT License.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Build and push

name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Push ghcr.io/gp-devenv/gp-ncs-devenv
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ubuntuVersion: ['22.04', '24.04']
        nodeVersion: ['18', '20', '22']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup buildx
        run: (cd src && ./scripts/buildx/setup.sh)
      - name: Authenticating
        run: echo $GHCR_IO_TOKEN | docker login ghcr.io -u gpfister --password-stdin
        env:
          GHCR_IO_TOKEN: ${{secrets.ghcr_io_token}}
      - name: Build and push to ghcr.io/gp-devenv/gp-ncs-devenv:${{ matrix.ubuntuVersion }}-${{ matrix.nodeVersion }}
        run: (cd src && ./scripts/buildx/push.sh $UBUNTU_VERSION $NODE_VERSION)
        env:
          UBUNTU_VERSION: ${{ matrix.ubuntuVersion }}
          NODE_VERSION: ${{ matrix.nodeVersion }}
  cleanup:
    runs-on: ubuntu-22.04
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cleanup
        uses: gp-devenv/gp-docker-image-cleanup@v2
        with:
          runAsUser: gpfister
          token: ${{ secrets.GHCR_IO_TOKEN }}
          retentionDays: 7
          isOwnedByOrganization: true
# End
